name: CI-Frontend-Workflow

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài đặt Node.js với phiên bản chỉ định
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Cài đặt dependencies cho frontend
      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: starter/frontend

      # Chạy linter cho mã nguồn frontend
      - name: Lint Frontend Code
        run: npm run lint
        working-directory: starter/frontend

      # Chạy tests frontend
      - name: Run Frontend Tests
        run: npm test -- --coverage
        working-directory: starter/frontend

      # Build ứng dụng frontend
      - name: Build Frontend Application
        run: npm run build
        working-directory: starter/frontend

      # Serve ứng dụng frontend (chỉ dành cho môi trường kiểm thử)
      - name: Serve Frontend Application
        run: npm run serve
        working-directory: starter/frontend

      # Hoàn thành
      - name: Completion Message
        run: |
          echo "Hello ${{ github.actor }}. You pushed to ${{ github.repository }} at $(date)."
